source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JCPageViewController_Example', :exclusive => true do
  pod "JCPageViewController", :path => "../"
  pod "Masonry"
end

target 'JCPageViewController_Tests', :exclusive => true do
  pod "JCPageViewController", :path => "../"
  pod "Masonry"
  
end
